//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaProducto
    {
        public int IdVentaProducto { get; set; }
        public Nullable<int> IdProductoSucursal { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> IdProducto { get; set; }
    
        public virtual ProductoSucursal ProductoSucursal { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
